Failing test - showcase DOM update from no events/with directive for binding events issue
livewire/livewire pull request #1745
Opened 2020-10-03 00:54 UTC by fabriciojs

This is a failing test for the case of DOM updating which misses updating the directive even binding.

There will be an issue for this soon.

2020-10-03 05:22 UTC, nuernbergerA requested changes

2020-10-03 05:22 UTC, nuernbergerA commented on tests/Browser/Actions/Test.php
> +                ->waitForLivewire()->pause(100)->assertSeeIn('@output', 'button with wire:clicked got triggered')
thats not how `waitForLivewire()` is designed
For multiple assertions and actions before livewire renders AGAIN
```php
waitForLivewire(function ($b) {
    $b->click('something')
})
// livewire has done its magic and you proceed here after all is rendered
```

sometimes its just a oneliner so you can just pass the single action like HigherOrderProxy stuff
```php
waitForLivewire()->click('something')
// livewire has done its magic and you proceed here after all is rendered
```

```php
            Livewire::visit($browser, Component::class)
                /**
                 * sibling buttons
                 */
                ->waitForLivewire()->press('@show.button.actions')
                ->assertPresent('@button.with-actions')
                ->waitForLivewire()->press('@button.with-click')
                ->assertSeeIn('@output', 'button with wire:clicked got triggered')
            ;
```

just to streamline, we use `click()` over `press()` in 99%

2020-10-03 05:22 UTC, nuernbergerA commented on tests/Browser/Actions/Test.php
> +    public function test_button_dom_update_click_event_with_id()
Due to **performance** reasons, we structured all browser **tests** to have **only one** test **method** per file and just chain all "real" tests within it.

To separate them we use doc-blocks and if needed a `->refresh()` call.

2020-10-03 05:24 UTC, nuernbergerA commented
Hey @fabriciojs,

thanks for your PR!
That's the way we like it, you deliver a failing test - we fix it :+1: 

Cheers Adrian

2020-10-03 13:38 UTC, fabriciojs commented
@nuernbergerA thanks for the review! I updated the test accordingly to your remarks.

Now the last assertion is the only failing part - `->assertSeeIn('@output', 'button with wire:clicked got triggered')` at line 136.

We will try explore on the solution as well - we can keep discussions here on any progress to keep everyone posted.

Thanks!

2020-10-19 16:23 UTC, carlalexander commented
Just wanted to tag in with a workaround if someone runs into this issue. I couldn't figure out why my modal wouldn't close after the content was swapped. I just added a random ID with `Str::random()` and the `wire:click` event was picked up.

```blade
<div class="mt-5 sm:grid sm:grid-cols-2 sm:gap-3 sm:grid-flow-row-dense">
    @if (empty($token))
        <button>{{ __('button.create') }}</x-button-primary>
        <button wire:click="$set('opened', false)">{{ __('button.cancel') }}</x-button-secondary>
    @else
        {{-- This needs an ID --}}
        <button id="{{ Str::random() }}" wire:click="$set('opened', false)">{{ __('button.close') }}</x-button-secondary>
    @endif
</div>
```

2020-10-28 17:44 UTC, calebporzio commented
Thanks for posting the solution @carlalexander - there is no good way for morphdom to know that those two conditionals are different, so it just tries to update one to the other.

Adding keys is the way to go here.

Closing this

2020-10-28 17:44 UTC, closed without merging