Improve performance by removing getClass()
livewire/livewire pull request #266
Opened 2019-09-13 20:27 UTC by intellow

Fixes #256 

Admittedly I don't really know what's going on here, but I do know that with `->getClass()` here, my delete function takes between 400ms and 800ms. When I remove it then it not only still works, but takes just about 50ms.

2019-09-13 20:55 UTC, intellow commented
A few other notes on this one. As an avid `dd()` developer, I narrowed down the slowness to this method. For my implementation, my `$parameter` was the following:

![image](https://user-images.githubusercontent.com/40676515/64894111-79b91580-d63e-11e9-9908-408e1391d7e5.png)

When I did `dd($parameter->getClass())` I got null, and then this line was trying to call `->name` on null, and this is where my performance issues came from. However, there is a `name` parameter on my variable, so it seems like we need to check for getClass() and if it's null then just do `$parameter->name`.

Like I said above, I'm not really sure what's going on in this code but it fixes my problem and passes CI. 

@jrseliga it looks like you committed this code originally. Does this look good or do you have any other input?

2019-09-13 21:55 UTC, tillkruss commented
Can you pull the output into a variable so it only called once?

2019-09-13 21:57 UTC, tillkruss requested changes

2019-09-13 21:57 UTC, tillkruss commented on src/Concerns/HandlesActions.php
> +                }
How about this?

```php
if ($class = $parameter->getClass()) {
    return app($class->name);
}

return app($parameter->name);
```

2019-09-13 22:13 UTC, intellow commented on src/Concerns/HandlesActions.php
> +                }
Looks good to me.

2019-09-18 02:06 UTC, calebporzio commented
Weird, I wonder if it's because the `rescue` helper calls `report($e)`, and maybe you have some error handling that takes a long time? Not sure.

I found a similar performance issue with the `report` method in the exception handler myself, but I can't replicate it to dig deeper.

Either way, I think this is a good code improvement anyways, although we probably don't need

2019-09-18 02:06 UTC, merged

2019-12-20 18:13 UTC, lancepioch commented
@all-contributors please add @intellow for maintenance