fix start variable
livewire/livewire pull request #7179
Opened 2023-10-28 19:30 UTC by osama-98

Fix the example of steaming the count down.

2023-10-28 21:12 UTC, SRWieZ requested changes
Hi! It should work with $start

Just tested it, the correct fix is changing <<<HTML to <<<'HTML'

https://www.php.net/manual/fr/language.types.string.php#language.types.string.syntax.nowdoc

2023-10-31 18:51 UTC, osama-98 commented
Hi @SRWieZ ,
Should I update this?

2023-10-31 19:05 UTC, osama-98 commented
@SRWieZ 
I have updated the pull-request. Please check.

2023-11-05 16:37 UTC, calebporzio commented
Good call, thank you!

2023-11-05 16:37 UTC, merged