Use redirect helper
livewire/livewire pull request #7258
Opened 2023-11-09 19:58 UTC by francoism90

Review the contribution guide first at: https://laravel-livewire.com/docs/2.x/contribution-guide

1️⃣ Is this something that is wanted/needed? Did you create a discussion about it first?

Yes, but it's a minor change.

2️⃣ Did you create a branch for your fix/feature? (Master branch PR's will be closed)

Yes

3️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.

No

4️⃣ Does it include tests? (Required)

No, this should already be included (doc change only)

5️⃣ Please include a thorough description (including small code snippets if possible) of the improvement and reasons why it's useful.

I think it's useful to use `$this->redirect(..)`, as some may overlook this.

Thanks for contributing! 🙌

2023-11-09 20:45 UTC, PerryvanderMeer requested changes

2023-11-09 20:45 UTC, PerryvanderMeer commented on docs/wire-submit.md
> +        $this->redirect('/posts);
Missing '

2023-11-10 12:21 UTC, levu42 commented
@francoism90 I suggest prefixing the PR title with `Docs: ` to make it clear it's about the docs, not about the source :)

2023-11-10 14:07 UTC, calebporzio commented
Great,t hank you!

2023-11-10 14:07 UTC, merged