Config the lifetime of temporary files
livewire/livewire pull request #7286
Opened 2023-11-15 04:44 UTC by mh828

Hello.
In order for the uploaded files to be adjustable in temporary mode, I made some changes in the program code that I don't think it was necessary to write a test for.

2023-12-08 13:35 UTC, PhiloNL requested changes
Please see the suggested changes. If you could add a test as well, that would be great.

2023-12-08 13:35 UTC, PhiloNL commented on src/Features/SupportFileUploads/FileUploadConfiguration.php
> +    public static function tempLifeTime()
```suggestion
    public static function temporaryFileRetentionTime()
```

2023-12-08 13:35 UTC, PhiloNL commented on src/Features/SupportFileUploads/FileUploadConfiguration.php
> +        return config('livewire.temporary_file_upload.temp_life_time') ?: 1440;//in minutes
```suggestion
        return config('livewire.temporary_file_upload.file_retention_time') ?: 60;
```

2023-12-08 13:35 UTC, PhiloNL commented on src/Features/SupportFileUploads/WithFileUploads.php
> +            $yesterdaysStamp = now()->addMinutes(-1 * FileUploadConfiguration::tempLifeTime())->timestamp;
```suggestion
            $retentionTimestamp = now()->subMinutes(FileUploadConfiguration:: temporaryFileRetentionTime())->timestamp;
```

2023-12-08 13:35 UTC, PhiloNL commented on src/Features/SupportFileUploads/WithFileUploads.php
>              if ($yesterdaysStamp > $storage->lastModified($filePathname)) {
```suggestion
            if ($retentionTimestamp > $storage->lastModified($filePathname)) {
```

2023-12-26 19:09 UTC, lrljoe commented
@PhiloNL noticed a couple of instances in your updates that use addMinutes(-1*Q) rather than subMinutes(Q), just (politely!) wondering why that approach?

2023-12-26 19:12 UTC, PhiloNL commented
> @PhiloNL noticed a couple of instances in your updates that use addMinutes(-1*Q) rather than subMinutes(Q), just (politely!) wondering why that approach?

That's exactly what I suggested in my review comments 😄 
https://github.com/livewire/livewire/pull/7286#discussion_r1420450699

2023-12-26 19:19 UTC, lrljoe commented
> > @PhiloNL noticed a couple of instances in your updates that use addMinutes(-1*Q) rather than subMinutes(Q), just (politely!) wondering why that approach?
> 
> @lrljoe that's exactly what I suggested to be changed in my review comments 😄 [#7286 (comment)](https://github.com/livewire/livewire/pull/7286#discussion_r1420450699)

Think festivities have corrupted my eyes... definitely read it differently on mobile, cheers for doing the needful.  Hopefully @mh828 can make the relevant changes :)

2024-01-04 15:30 UTC, calebporzio commented
Closing until there's more demand for this - it's a hard thing to test and anticipate issues so unfortunately it's not an easy merge for me. Thanks!

2024-01-04 15:30 UTC, closed without merging