Fix Livewire component key generation across load balanced servers
livewire/livewire pull request #7751
Opened 2024-01-19 01:30 UTC by calebporzio

Because Livewire child component keys are random strings and are generated at Laravel compile-time, load-balanced environments experience bugs because the Livewire component keys are different across servers.

This PR makes Livewire component "key" generation deterministic across load balanced environments by using the current Blade view and an incrementing counter as the key instead of a random string.

2024-01-19 15:12 UTC, nuernbergerA commented
@calebporzio performance wise the new implementation seems more "heavy" then a simple `Str::random`

wouldn't it be better to replace and fetch a possible key upfront and only generate when non was provided?

2024-01-19 15:18 UTC, nuernbergerA requested changes

2024-01-19 15:18 UTC, nuernbergerA commented on src/Mechanisms/RenderComponent.php
> +use Livewire\Livewire;
```suggestion
```

unused import

2024-01-19 15:18 UTC, nuernbergerA commented on src/Mechanisms/RenderComponent.php
>          }, $expression);
```suggestion
        $key = null;
        $pattern = "/,\s*?key\(([\s\S]*)\)/"; // everything between ",key(" and ")"

        $expression = preg_replace_callback($pattern, function ($match) use (&$key) {
            $key = trim($match[1]);
            return "";
        }, $expression);
        
        if (! $key) {
                $key = app(\Livewire\Mechanisms\ExtendBlade\DeterministicBladeKeys::class)->generate();
                $key = "'{$key}'";
        }
```

maybe something like this

2024-01-20 17:37 UTC, merged

2024-03-15 02:54 UTC, dwightwatson commented
This PR may have been the cause of the issues discussed here: https://github.com/livewire/livewire/discussions/7934

Can see above that `enflow/livewire-twig` had to override this change to get around it.

I've only just run into it after upgrading to Laravel 11 but looks like people are seeing it on Laravel 10 as well. Generally isolated to Linux rather than Mac which.

2025-04-08 13:46 UTC, MickProPay commented
I dont think this solved the problem guys. We still having issues and unless our forge blancers is set to IP hash livewire is a problem.

2025-04-23 05:22 UTC, ettiennelouw commented
We are also still having the same issue and need our load balancer on IPHash, some of the filament panel components are also having issues.

2025-04-30 15:31 UTC, peterjbassi commented
Also experiencing this issue with Livewire 3.6.3 in GCP Cloud Run behind a load balancer, namely with Filament components reaching out to `/livewire/update`. Enabling sticky sessions in the load balancer or reducing to only 1 container instance both work around the problem, but neither are a solution for us given the nature of our application.

2025-05-01 05:31 UTC, joshhanley commented
@MickProPay @ettiennelouw and @peterjbassi thanks for reporting! When you're all saying your having issues, can you please be specific about exactly what the issues you are seeing, with error messages and screenshots and a description of what is happening, so we can try and replicate it so we can investigate it? Thanks!

2025-05-01 14:07 UTC, peterjbassi commented
@joshhanley 
```
laravel/framework 11.44.7
filament/filament 3.3.13
livewire/livewire 3.6.3
```

I first encountered this issue when I deployed a fully developed Filament application to GCP Cloud Run (serverless) with 3 container instances. A resource index (table) page with a couple of chart widgets would break (displaying a basic Laravel 500 error modal) after the initial payload had rendered. Chrome devtools showed that some of the `/livewire/update` requests for the chart widgets returning a `500`. The number of requests that failed varied with page reload. I had never experienced that problem in the prior two months of development on my local machine with a single Docker container running the app.

As part of my investigation, I created a fresh Laravel project, installed Filament, and put 10 simple bar chart widgets on the default dashboard. The same issue presented itself when I deployed the new project to Cloud Run in a different GCP project. 

Through testing/tweaking I've encountered a variety of symptoms, including:
- `500` responses with no exception/stacktrace (`APP_ENV=development, APP_DEBUG=true`)
- Partial `200` responses missing various random pieces of the chart widget mark-up
- `development.ERROR: Livewire encountered a missing root tag when trying to render a component.`

The following configurations have "fixed" the issue:
- A revision with a single container instance
- A revision with multiple container instances and Cloud Run's Session Affinity feature turned on
- A revision with multiple container instances and a GCS bucket mounted at `./storage/framework/views` so that all container instances were sharing a common view cache

It was that last working configuration that really pushed me to thinking this was a Livewire load-balancer-related Laravel view/blade cache problem.

The network tab ends up looking like this, with the count and position of failed requests different on every page load:
<img width="1262" alt="image" src="https://github.com/user-attachments/assets/57ce5a9d-1f73-461e-b8ee-e4b2fc818e43" />

That's probably the best I can provide right now. I'm not familiar with Livewire's internals. 

Happy to answer any questions.

2025-05-06 19:03 UTC, peterjbassi commented
Created a small app to demonstrate: https://github.com/peterjbassi/filamentapp

2025-05-06 22:46 UTC, joshhanley commented
@peterjbassi thanks!

2025-05-08 23:40 UTC, joshhanley commented
Going to keep this discussion going in #9323