Add support for "paginationSimpleView()" method in components
livewire/livewire pull request #8331
Opened 2024-04-20 19:49 UTC by iBotPeaches

#1304

## Problem

If you switch to a paginator that uses simple or even the cursor offset based paginator. You lose the ability to configure the exact view used. Your only configuration option relies on the `paginationTheme` property which forces the `livewire` prefix, thus preventing the same override that exists on the `paginationView`.

## Cause

The function `paginationSimpleView` has no override, unlike the corresponding `paginationView` function: https://github.com/livewire/livewire/blob/main/src/Features/SupportPagination/SupportPagination.php#L127-L135

## Solution

Much like done in this [commit](https://github.com/livewire/livewire/commit/12130528b493cfe5260d989fc77f34ac30e746af), add override support for simple based paginators.

2024-04-20 20:06 UTC, PerryvanderMeer requested changes
Can you please add a short description of the existence of `paginationSimpleView()` [to the docs](https://livewire.laravel.com/docs/pagination#using-custom-pagination-views)?

2024-04-20 20:12 UTC, iBotPeaches commented
> Can you please add a short description of the existence of `paginationSimpleView()` [to the docs](https://livewire.laravel.com/docs/pagination#using-custom-pagination-views)?

Adjusted some parts of docs to call out the option you have here.

2024-04-20 20:20 UTC, PerryvanderMeer requested changes

2024-04-20 20:20 UTC, PerryvanderMeer commented on docs/pagination.md
> +public function paginationSimpleView()
Please add a new line in between.

2024-04-20 20:31 UTC, PerryvanderMeer approved these changes

2024-04-24 15:51 UTC, calebporzio commented
Perfect, thank you!

2024-04-24 15:51 UTC, merged