fix: function name typo
livewire/livewire pull request #8884
Opened 2024-09-25 03:30 UTC by YilanBoy

Fix function name typo in `js/plugins/navigate/index.js`

```js
// From `Libaries` to `Libraries`
function fireEventForOtherLibrariesToHookInto(name, detail) {
    // ...
}
```

2024-09-29 04:35 UTC, lrljoe commented
Make sure your source is up to date, as there seems to be a lot of unrelated differences in this PR.

2024-09-29 04:40 UTC, lrljoe requested changes
It seems your branch is out of date


Please update it to avoid conflicting changes 
Please ensure that a PR addresses a single issue, and do not try to address multiple items in a single PR

2024-09-29 04:40 UTC, lrljoe commented on dist/livewire.esm.js
> -// ../../../../usr/local/lib/node_modules/@alpinejs/intersect/dist/module.cjs.js
Unrelated to the stated PR purpose

2024-09-29 04:40 UTC, lrljoe commented on dist/livewire.esm.js
> -  "../../../../usr/local/lib/node_modules/@alpinejs/persist/dist/module.cjs.js"(exports, module) {
Unrelated to the stated PR purpose

2024-09-29 04:40 UTC, lrljoe commented on dist/livewire.esm.js
> -  "../../../../usr/local/lib/node_modules/@alpinejs/focus/dist/module.cjs.js"(exports, module) {
Unrelated to the stated PR purpose

2024-09-29 04:40 UTC, lrljoe commented on dist/livewire.esm.js
> -// ../../../../usr/local/lib/node_modules/@alpinejs/focus/dist/module.cjs.js
Unrelated to the stated PR purpose

2024-09-29 04:40 UTC, lrljoe commented on dist/livewire.esm.js
> -  "../../../../usr/local/lib/node_modules/@alpinejs/collapse/dist/module.cjs.js"(exports, module) {
Unrelated to the stated PR purpose

2024-09-29 04:40 UTC, lrljoe commented on dist/livewire.esm.js
> -            destroyTree(clone2);
Unrelated to the stated PR purpose

2024-09-29 04:40 UTC, lrljoe commented on dist/livewire.esm.js
> -            destroyTree(lookup[key]);
Unrelated to the stated PR purpose

2024-09-29 04:40 UTC, lrljoe commented on dist/livewire.esm.js
> -          destroyTree(el2);
Unrelated to the stated PR purpose

2024-09-29 04:40 UTC, lrljoe commented on dist/livewire.esm.js
> -        clone2.remove();
Unrelated to the stated PR purpose

2024-09-29 04:40 UTC, lrljoe commented on dist/livewire.esm.js
> -      initInterceptors(stores[name]);
Unrelated to the stated PR purpose

2024-09-29 04:40 UTC, lrljoe commented on dist/livewire.esm.js
> -    var booleanAttributes = /* @__PURE__ */ new Set([
Unrelated to the stated PR purpose

2024-09-29 04:40 UTC, lrljoe commented on dist/livewire.esm.js
> -        cleanupElement(el);
Unrelated to the stated PR purpose

2024-09-29 04:40 UTC, lrljoe commented on dist/livewire.esm.js
> -    function getUtilities(el) {
Unrelated to the stated PR purpose

2024-09-29 04:40 UTC, lrljoe commented on dist/livewire.esm.js
>          Object.defineProperty(obj, `$${name}`, {
Unrelated to the stated PR purpose

2024-09-29 04:40 UTC, lrljoe commented on dist/livewire.esm.js
>      function injectMagics(obj, el) {
Unrelated to the stated PR purpose

2024-09-29 04:40 UTC, lrljoe commented on dist/livewire.esm.js
>      function cleanupElement(el) {
Unrelated to the stated PR purpose

2024-09-29 04:40 UTC, lrljoe commented on dist/livewire.esm.js
> -// ../alpine/packages/alpinejs/dist/module.cjs.js
Unrelated to the stated PR purpose

2024-09-29 04:40 UTC, lrljoe commented on dist/livewire.esm.js
> -          if (!(key in lookup))
Unrelated to the stated PR purpose

2024-09-29 04:40 UTC, lrljoe commented on dist/livewire.esm.js
> -              if (el.getBoundingClientRect().height == full) {
Unrelated to the stated PR purpose

2024-09-29 04:40 UTC, lrljoe commented on dist/livewire.esm.js
> -// ../alpine/packages/anchor/dist/module.cjs.js
Unrelated to the stated PR purpose

2024-09-29 04:40 UTC, lrljoe commented on dist/livewire.esm.js
> -  "../alpine/packages/morph/dist/module.cjs.js"(exports, module) {
Unrelated to the stated PR purpose

2024-09-29 04:40 UTC, lrljoe commented on dist/livewire.esm.js
> -          if (name === "style")
Unrelated to the stated PR purpose

2024-09-29 04:40 UTC, lrljoe commented on dist/livewire.esm.js
> -          if (name === "style")
Unrelated to the stated PR purpose

2024-09-29 04:40 UTC, lrljoe commented on dist/livewire.esm.js
> -// ../../../../usr/local/lib/node_modules/@alpinejs/mask/dist/module.cjs.js
Unrelated to the stated PR purpose

2024-09-29 15:36 UTC, YilanBoy commented
Hi @lrljoe 

I only change the function name in file `js/plugins/navigate/index.js`.

The other files change is auto generated by `npm run build` command. Should I remove these auto generated files?

2024-10-11 12:00 UTC, PhiloNL commented
Hi @YilanBoy,
Could you please update the PR without the dist files so it only includes your changes? We can build in on our end to see if something is up with the build process.

2024-10-14 02:12 UTC, closed without merging

2024-10-14 02:22 UTC, YilanBoy commented
Hi @PhiloNL 

Got it! I will open another pull request
Thank you!